/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trunk.model;

/**
 *
 * @author Ycaro_2
 */
public enum TipoPacote { 
        LOGIN,SUCESSO_LOGIN, FALHA_LOGIN,
	CADASTRO, SUCESSO_CADASTRO, NAO_CADASTRADO, COMECA_PARTIDA, PROCURAR_OPONENTE, EXISTE_PARTIDA, LIBERAR_PARTIDA, PARTIDA_LIBERADA, ESPERAR_OPONENTE, CANCELAR_PARTIDA, CANCELAR_PEDIDO_PARTIDA, PARTIDA_CANCELADA, TIRO, USUARIOS_OFFLINES, CARREGAR_USUARIO_CHAT, USUARIO_CHAT_CARREGADO, ENVIAR_CHAT_MESSAGEM, MESSAGEM_RECEBIDA, CONVITE_ACEITO, CONVITE_RECUSADO, START_CHAT, ENCERRAR_CHAT, ENCERRAR_CONEXAO_SAIR, CONVITE_CHAT, SALA_CHAT_LIBERADA, LIBERAR_SALA_CHAT, SALA_CHAT_NAO_LIBERADA;
    
}
